name: JaCoCo Report

# This workflow will create a coverage report for the project, changed files, and add it to the
# Pull-Request as a comment.

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Coverage
        run: |
          chmod +x gradlew
          ./gradlew test

      # Create the coverage report and add it to the PR as a comment
      - name: Add Jacoco coverage to PR
        id: jacocoPR
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/**/build/reports/jacoco/**/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          # default = 80 for both
          min-coverage-overall: 70
          min-coverage-changed-files: 75
          debug-mode: false

      - name: Get the Coverage info
        run: |
          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"

      # If the minimum coverage is not met, the action will fail
      - name: Fail PR if overall coverage is less than required
        if: ${{ steps.jacoco.outputs.coverage-overall < 50.0 }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Overall coverage is less than 50%!')